### ISSUE TITLE
How can use Splunk with Phobos?

### ISSUE THREAD

**Issue by seungyongshim** [petabridge/phobos-issues#24]
Excuse, me.

How can use Splunk with Phobos?

@Aaronontheweb

**Comment by Aaronontheweb** [comment]
Off the top of my head, probably the easiest way to do this for tracing is via the OpenTelemetry support for Splunk: https://www.splunk.com/en_us/data-insider/what-is-opentelemetry.html#opentracing

You can use the OTel OpenTracing shim to run inside Phobos and gather traces from it that way: https://www.nuget.org/packages/OpenTelemetry.Shims.OpenTracing/

As for metrics - right now I don't believe App.Metrics supports Splunk and it probably won't, since Splunk's model relies on log aggregation which isn't really compatible with how App.Metrics does things. 

We _want_ to support OpenTelemetry all the way down the stack inside Phobos, as that would make things a lot easier, but the OTel metrics specification is still in beta https://github.com/open-telemetry/opentelemetry-specification/tree/main/specification/metrics and the .NET implementation won't have the low-level tools it needs to be implemented until after .NET 6 ships in November https://github.com/open-telemetry/opentelemetry-dotnet/issues/1501

Does that help?
